apiVersion: v1
kind: Pod
metadata:
  name: webapp-0
  labels:
    app: webapp
    release: "0"
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---

apiVersion: v1
kind: Pod
metadata:
  name: webapp-0-5
  labels:
    app: webapp
    release: 0-5
spec:
  containers:
    - name: webapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---

apiVersion: v1
kind: Pod
metadata:
  name: queue-app
  labels:
    app: queue
    release: "1"
spec:
  containers:
    - name: queueapp
      image: richardchesterwood/k8s-fleetman-queue:release1