apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      containers: 
        - name: mongodb
          image: mongo:3.6.5-jessie
          volumeMounts:
            - name: mongo-persistence-path
              mountPath: /data/db
      volumes:
        - name: mongo-persistence-path
          persistentVolumeClaim:
            claimName: mongo-storage

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017