apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mongo-storage
spec:
  storageClassName: my-local-storage
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolume
metadata: 
  name: localhost-storage
spec:
  storageClassName: my-local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/dineshgaglani/personalProjects/kubernetesUdemyCourse/tryouts/data
    type: DirectoryOrCreate 


