apiVersion: v1
kind: Service
metadata:
  name: webapp-access

spec:
  
  selector:
    app: webapp

  type: NodePort

  ports:
    - name: http
      port: 80
      nodePort: 30080

---

apiVersion: v1
kind: Service
metadata:
  name: queue-access
spec:
  selector:
    app: queue
    release: "1"
  type: NodePort
  ports:
    - name: http
      port: 8161
      nodePort: 30010

---

apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  type: ClusterIP
  ports:
    - name: tcp
      port: 3306