apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp

spec:
  replicas: 2
  selector:
     matchLabels:
       app: webapp

  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---

apiVersion: v1
kind: Pod
metadata:
  name: queue-app
  labels:
    app: queue
    release: "1"
spec:
  containers:
    - name: queueapp
      image: richardchesterwood/k8s-fleetman-queue:release1

---

apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:5 
      env: 
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: fleetman