apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  type: NodePort
  selector:
    app: queue
  ports:
    - name: http
      port: 8161
      nodePort: 30010
    - name: endpoint
      port: 61616

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  type: NodePort
  selector:
    app: position-tracker
  ports:
    - name: http
      port: 8080
      nodePort: 30020

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
      nodePort: 30030

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
      nodePort: 30080